// Curated, whitelisted lucide-react icon names offered in the subcategory
// icon picker, grouped by the category they're most likely useful for (the
// picker itself is available for any category-grouping is just for
// discoverability, not a hard restriction).
export const ICON_GROUPS = [
  {
    label: "Aprender",
    icons: [
      "Code",
      "Languages",
      "Building2",
      "Leaf",
      "Container",
      "Atom",
      "Cloud",
      "Database",
      "GitBranch",
      "Terminal",
      "FlaskConical",
      "Network",
      "Brain",
      "BookOpen",
      "GraduationCap",
      "PenTool",
      "Calculator",
    ],
  },
  {
    label: "Salud",
    icons: [
      "Dumbbell",
      "HeartPulse",
      "Stethoscope",
      "Pill",
      "Syringe",
      "Bandage",
      "Activity",
      "Bike",
      "Footprints",
      "Salad",
      "Apple",
      "Droplet",
      "Bed",
      "Thermometer",
      "CalendarCheck",
      "Smile",
      "Eye",
    ],
  },
  {
    label: "Finanzas",
    icons: [
      "Wallet",
      "PiggyBank",
      "CreditCard",
      "Coins",
      "TrendingUp",
      "Receipt",
      "Landmark",
      "DollarSign",
      "Banknote",
    ],
  },
  {
    label: "Descanso consciente",
    icons: [
      "Sparkles",
      "Moon",
      "Sun",
      "Wind",
      "Flower2",
      "Coffee",
      "Bath",
      "CloudRain",
      "Headphones",
      "Feather",
    ],
  },
  {
    label: "Trabajo",
    icons: [
      "Briefcase",
      "Laptop",
      "Mail",
      "Calendar",
      "Presentation",
      "ClipboardList",
      "Phone",
      "FileText",
      "Users",
    ],
  },
  {
    label: "Diversión",
    icons: [
      "Trophy",
      "Medal",
      "Timer",
      "Target",
      "Palette",
      "Camera",
      "Headphones",
      "Music",
      "Book",
      "Pencil",
      "Gamepad2",
      "Puzzle",
      "TreePine",
      "Mountain",
      "Sunrise",
      "Compass",
      "Map",
      "Tent",
    ],
  },
  {
    label: "General",
    icons: [
      "Star",
      "Heart",
      "Zap",
      "Paintbrush",
      "Plane",
      "House",
      "PawPrint",
      "Baby",
      "Car",
      "ShoppingCart",
      "Globe",
    ],
  },
] as const;

export const ICON_OPTIONS = ICON_GROUPS.flatMap((group) => group.icons);
export type IconOption = (typeof ICON_OPTIONS)[number];
